<?php

namespace MehdiBundle\Entity;

/**
 * ArticleSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
